### ISSUE TITLE
部署报错

### ISSUE THREAD

**Issue by davuses** [dufu1991/simple-cloud-music#16]
问题1：

readme 里这一段： 

> 设备安装好 node 环境之后，进入工程目录，执行 node i 安装依赖。

`node i` 命令是不是应该是 `npm install` ?

问题2：
```
[!] Error: Could not resolve './pages/Version.svelte' from src/routes.js
Error: Could not resolve './pages/Version.svelte' from src/routes.js
    at error (/root/simple-cloud-music/node_modules/rollup/dist/shared/rollup.js:198:30)
    at ModuleLoader.handleResolveId (/root/simple-cloud-music/node_modules/rollup/dist/shared/rollup.js:22287:24)
    at /root/simple-cloud-music/node_modules/rollup/dist/shared/rollup.js:22250:26
```
应该是文件名大小写问题 ， `src/pages/version.svelte` 文件名改为  `src/pages/Version.svelte` 就好了。

问题3：
```
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)                          
node_modules/axios/package.json (2:8)                                                                              
1: {                                                                                                               
2:   "name": "axios",                                                                                              
           ^                                                                                                       
3:   "version": "0.21.4",                                                                                          
4:   "description": "Promise based HTTP client for the browser and node.js",                                                                                                                                                           
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)                              
    at error (/root/simple-cloud-music/node_modules/rollup/dist/shared/rollup.js:198:30)                           
    at Module.error (/root/simple-cloud-music/node_modules/rollup/dist/shared/rollup.js:12560:16)                                                                                                                                      
    at Module.tryParse (/root/simple-cloud-music/node_modules/rollup/dist/shared/rollup.js:12937:25)                                                                                                                                   
    at Module.setSource (/root/simple-cloud-music/node_modules/rollup/dist/shared/rollup.js:12842:24)              
    at ModuleLoader.addModuleSource (/root/simple-cloud-music/node_modules/rollup/dist/shared/rollup.js:22090:20)  
```
这个问题不知道怎么解决

node 版本为 v18.12.0

**Comment by dufu1991** [comment]
1和2已修改。3我这边没有出现，你试试降低node版本。感谢你的时间和细心。

**Comment by davuses** [comment]
> 

@dufu1991  可以在文档里说明部署的 node 版本吗？

**Comment by dufu1991** [comment]
我的 node 是 v16.15.0，npm 是 6.14.17，本地开发正常。
